
server:
  port: 5000

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/videos/**